# Generated by Django 5.1.7 on 2025-03-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Login')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
            ],
        ),
    ]
