# Generated by Django 5.1.7 on 2025-03-12 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя клиента')),
                ('last_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Фамилия клиента')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
            ],
            options={
                'ordering': ['last_name', 'name', 'phone_number'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birdth_data', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'ordering': ['last_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Услуга')),
                ('price', models.IntegerField(verbose_name='Примерная стоимость')),
                ('duration', models.IntegerField(verbose_name='Продолжительность (минуты)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='Назначенная дата')),
                ('record_time', models.TimeField(verbose_name='Назначенное время')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации записи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saloon.client', verbose_name='Клиент')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saloon.employee', verbose_name='Мастер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saloon.service', verbose_name='Услуга')),
            ],
            options={
                'ordering': ['record_date', 'record_time'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.ManyToManyField(related_name='specialization', to='saloon.service', verbose_name='Услуги мастера'),
        ),
    ]
